export type ProviderCategory = 'llm' | 'tts' | 'stt';

export interface ProviderLink {
  id: string;
  name: string;
  category: ProviderCategory;
  keyUrl: string;
  docsUrl?: string;
  freeTier: boolean;
  limits: string;
  freeTierDetail: string;
  description: string;
  supportsVision?: boolean;
  supportsRussian?: boolean;
  requiresCard?: boolean;
}

export const PROVIDER_LINKS: ProviderLink[] = [
  // === LLM ===
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'llm',
    keyUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://openrouter.ai/docs',
    freeTier: true,
    limits: '20 RPM / 50 RPD (1000 RPD при $10)',
    freeTierDetail: '25+ free моделей, :free vision',
    description: 'Самый удобный старт, 25+ бесплатных моделей с vision',
    supportsVision: true,
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    category: 'llm',
    keyUrl: 'https://build.nvidia.com',
    docsUrl: 'https://docs.api.nvidia.com/nim/reference',
    freeTier: true,
    limits: '~40 RPM',
    freeTierDetail: '189+ моделей, без карты',
    description: 'OpenAI-совместимый, нужна верификация телефона',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'google-ai',
    name: 'Google AI Studio',
    category: 'llm',
    keyUrl: 'https://aistudio.google.com/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    freeTier: true,
    limits: '5-15 RPM / 250 RPD (Flash)',
    freeTierDetail: 'Gemini 2.5 Flash/Pro vision, без карты',
    description: 'Лучший free tier по токенам, vision',
    supportsVision: true,
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'llm',
    keyUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/quickstart',
    freeTier: true,
    limits: '30 RPM / 14400 RPD (Llama 3.1 8B)',
    freeTierDetail: 'Самый быстрый inference',
    description: 'Llama 4 Scout с vision, без карты',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'llm',
    keyUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai/',
    freeTier: true,
    limits: 'Free mode, ~1B токенов/мес',
    freeTierDetail: 'Pixtral Large vision',
    description: 'Pixtral Large (vision)',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    category: 'llm',
    keyUrl: 'https://github.com/marketplace/models',
    docsUrl: 'https://docs.github.com/en/github-models',
    freeTier: true,
    limits: '40+ моделей, rate limit по GitHub',
    freeTierDetail: 'GPT-4o, o1, Claude 3.5, DeepSeek-R1',
    description: 'Бесплатно для разработчиков, нужен GitHub аккаунт',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    category: 'llm',
    keyUrl: 'https://cloud.cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai/',
    freeTier: false,
    limits: '$5 credit на старт (free tier retired July 2026)',
    freeTierDetail: 'Ultra-fast inference',
    description: 'Ultra-fast, но бесплатность ограничена',
    supportsVision: false,
    requiresCard: false,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    category: 'llm',
    keyUrl: 'https://cloud.sambanova.ai',
    docsUrl: 'https://docs.sambanova.ai/',
    freeTier: true,
    limits: '20 запросов/день',
    freeTierDetail: 'Llama 4 Maverick, Llama 3.2 90B Vision',
    description: 'Llama 4 Maverick, Vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'llm',
    keyUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs',
    freeTier: false,
    limits: 'Платно, $5 стартовых кредитов',
    freeTierDetail: 'GPT-4o, o1',
    description: 'Для fallback',
    supportsVision: true,
    requiresCard: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'llm',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com/',
    freeTier: false,
    limits: 'Платно',
    freeTierDetail: 'Claude 3.5',
    description: 'Для fallback',
    supportsVision: true,
    requiresCard: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    category: 'llm',
    keyUrl: 'https://dash.cloudflare.com/?to=/:account/workers/ai',
    docsUrl: 'https://developers.cloudflare.com/workers-ai/',
    freeTier: true,
    limits: '10 000 Neurons/день',
    freeTierDetail: 'Llama 3.2 11B Vision, Whisper, без карты',
    description: 'Хорош как fallback для vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'llm',
    keyUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/',
    freeTier: true,
    limits: '1000 запросов/мес (Trial)',
    freeTierDetail: 'Command A, Embed, без карты',
    description: 'Command A, бесплатный trial',
    supportsVision: false,
    requiresCard: false,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    category: 'llm',
    keyUrl: 'https://huggingface.co/settings/tokens',
    docsUrl: 'https://huggingface.co/docs/inference-providers',
    freeTier: true,
    limits: '300 запросов/час',
    freeTierDetail: '100k+ моделей, включая vision',
    description: 'Нужен HF аккаунт',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'llm',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://api-docs.deepseek.com/',
    freeTier: true,
    limits: 'Free tier через API, очень дёшево',
    freeTierDetail: 'DeepSeek-V3, R1, иногда free trial',
    description: 'Очень дешёвый',
    supportsVision: false,
    requiresCard: false,
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'llm',
    keyUrl: 'https://api.together.xyz/settings/api-keys',
    docsUrl: 'https://docs.together.ai/',
    freeTier: true,
    limits: '$5 кредитов на старт',
    freeTierDetail: 'Llama 3.3 70B, Qwen 2.5 VL vision',
    description: 'Qwen VL vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'llm',
    keyUrl: 'https://fireworks.ai/account/api-keys',
    docsUrl: 'https://docs.fireworks.ai/',
    freeTier: true,
    limits: '$1 кредит, потом pay-as-you-go',
    freeTierDetail: 'Llama 3.2 Vision, быстрый',
    description: 'Быстрый inference',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    category: 'llm',
    keyUrl: 'https://deepinfra.com/dash/api_keys',
    docsUrl: 'https://deepinfra.com/docs',
    freeTier: true,
    limits: '$1 кредит, pay-as-you-go',
    freeTierDetail: 'Llama 3.2 90B Vision, Qwen 2.5 VL',
    description: 'Llama 3.2 Vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'novita',
    name: 'Novita AI',
    category: 'llm',
    keyUrl: 'https://novita.ai/settings/key-management',
    docsUrl: 'https://docs.novita.ai/',
    freeTier: true,
    limits: '$0.5 кредит на старт',
    freeTierDetail: 'Llama 3.2 Vision, Qwen VL',
    description: 'Llama 3.2 Vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    category: 'llm',
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    docsUrl: 'https://docs.siliconflow.cn/',
    freeTier: true,
    limits: 'Free tier, щедрый',
    freeTierDetail: 'Qwen 2.5 VL, DeepSeek, китайский провайдер',
    description: 'Щедрый free tier',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (Z.ai)',
    category: 'llm',
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    docsUrl: 'https://open.bigmodel.cn/dev/howuse/introduction',
    freeTier: true,
    limits: 'GLM-4.6V-Flash, 1 concurrent',
    freeTierDetail: 'GLM-4V, бесплатный vision',
    description: 'GLM-4V vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI',
    category: 'llm',
    keyUrl: 'https://platform.moonshot.cn/console/api-keys',
    docsUrl: 'https://platform.moonshot.cn/docs',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: 'Kimi Vision, китайский',
    description: 'Kimi Vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: '01ai',
    name: '01.AI',
    category: 'llm',
    keyUrl: 'https://platform.01.ai',
    docsUrl: 'https://platform.01.ai/docs',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: 'Yi-Vision',
    description: 'Yi-Vision',
    supportsVision: true,
    requiresCard: false,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'llm',
    keyUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai/',
    freeTier: true,
    limits: '$5 кредитов/мес (Pro)',
    freeTierDetail: 'Sonar, online search, для SEO полезен',
    description: 'Не для vision, но для SEO',
    supportsVision: false,
    requiresCard: false,
  },
  {
    id: 'custom',
    name: 'Custom OpenAI-compatible',
    category: 'llm',
    keyUrl: '',
    docsUrl: '',
    freeTier: true,
    limits: '—',
    freeTierDetail: 'LM Studio, Ollama, vLLM, локальный endpoint',
    description: 'Любой OpenAI-совместимый endpoint',
    supportsVision: true,
    requiresCard: false,
  },

  // === TTS ===
  {
    id: 'gemini',
    name: 'Google Gemini TTS',
    category: 'tts',
    keyUrl: 'https://aistudio.google.com/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/speech',
    freeTier: true,
    limits: 'Free quota',
    freeTierDetail: '200+ голосов, отличный русский',
    description: 'Тот же ключ что для LLM, лучший RU',
    supportsVision: false,
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'tts',
    keyUrl: 'https://elevenlabs.io/app/settings/api-keys',
    docsUrl: 'https://elevenlabs.io/docs',
    freeTier: true,
    limits: '10 000 символов/мес',
    freeTierDetail: 'Multilingual v2, клонирование',
    description: 'Лучшее качество',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'speechify',
    name: 'Speechify',
    category: 'tts',
    keyUrl: 'https://platform.speechify.ai/api-keys',
    docsUrl: 'https://docs.sws.speechify.com/',
    freeTier: true,
    limits: 'Free tier ограничен',
    freeTierDetail: '1000+ голосов, 50+ языков',
    description: 'Много голосов',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'openai',
    name: 'OpenAI TTS',
    category: 'tts',
    keyUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs/guides/text-to-speech',
    freeTier: false,
    limits: '$15 / 1M символов',
    freeTierDetail: 'tts-1, tts-1-hd',
    description: 'Простой, но не free',
    supportsRussian: false,
    requiresCard: true,
  },
  {
    id: 'polly',
    name: 'Amazon Polly',
    category: 'tts',
    keyUrl: 'https://console.aws.amazon.com/iam',
    docsUrl: 'https://docs.aws.amazon.com/polly/',
    freeTier: true,
    limits: '5M символов / 12 мес',
    freeTierDetail: 'Нейронные голоса, AWS SigV4',
    description: 'Нужен JSON ключ',
    supportsRussian: true,
    requiresCard: true,
  },
  {
    id: 'qwen',
    name: 'Qwen3-TTS',
    category: 'tts',
    keyUrl: 'https://dashscope.console.aliyun.com/apiKey',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio/developer-reference/qwen-tts',
    freeTier: true,
    limits: '1M символов free',
    freeTierDetail: '49 голосов, 10 языков',
    description: 'Alibaba Cloud',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'azure',
    name: 'Microsoft Azure TTS',
    category: 'tts',
    keyUrl: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.CognitiveServices%2Faccounts',
    docsUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech',
    freeTier: true,
    limits: '500 000 символов/мес (F0)',
    freeTierDetail: 'Нейронные голоса, отличный RU, очень щедрый',
    description: 'Очень щедрый free tier',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud TTS',
    category: 'tts',
    keyUrl: 'https://console.cloud.google.com/apis/library/texttospeech.googleapis.com',
    docsUrl: 'https://cloud.google.com/text-to-speech/docs',
    freeTier: true,
    limits: '4M Standard / 1M WaveNet / мес',
    freeTierDetail: '380+ голосов, 75+ языков',
    description: 'Много голосов',
    supportsRussian: true,
    requiresCard: true,
  },
  {
    id: 'cartesia',
    name: 'Cartesia Sonic 3',
    category: 'tts',
    keyUrl: 'https://play.cartesia.ai/keys',
    docsUrl: 'https://docs.cartesia.ai/',
    freeTier: true,
    limits: 'Free tier, 40ms latency',
    freeTierDetail: 'Самый низкий latency, SSM',
    description: 'Ultra low latency',
    supportsRussian: false,
    requiresCard: false,
  },
  {
    id: 'hume',
    name: 'Hume AI Octave 2',
    category: 'tts',
    keyUrl: 'https://platform.hume.ai/settings/keys',
    docsUrl: 'https://dev.hume.ai/docs',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: 'Эмоционально-осознанная, контекстная',
    description: 'Эмоциональная озвучка',
    supportsRussian: false,
    requiresCard: false,
  },
  {
    id: 'deepgram',
    name: 'Deepgram Aura-2',
    category: 'tts',
    keyUrl: 'https://console.deepgram.com/',
    docsUrl: 'https://developers.deepgram.com/docs/tts',
    freeTier: true,
    limits: '$200 кредитов на старт, pay-as-you-go',
    freeTierDetail: 'Domain-tuned pronunciation',
    description: 'Точность в регулируемых отраслях',
    supportsRussian: false,
    requiresCard: false,
  },
  {
    id: 'playht',
    name: 'PlayHT',
    category: 'tts',
    keyUrl: 'https://play.ht/app/api-access',
    docsUrl: 'https://docs.play.ht/',
    freeTier: true,
    limits: 'Free tier ограничен',
    freeTierDetail: '900+ голосов, клонирование',
    description: 'Много голосов + клонирование',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'resemble',
    name: 'Resemble AI',
    category: 'tts',
    keyUrl: 'https://app.resemble.ai/',
    docsUrl: 'https://docs.resemble.ai/',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: 'Клонирование, emotion control',
    description: 'Клонирование + эмоции',
    supportsRussian: false,
    requiresCard: false,
  },
  {
    id: 'murf',
    name: 'Murf AI',
    category: 'tts',
    keyUrl: 'https://murf.ai/api',
    docsUrl: 'https://murf.ai/api/docs',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: '120+ голосов, синхронизация с видео',
    description: 'Синхронизация с видео',
    supportsRussian: false,
    requiresCard: false,
  },
  {
    id: 'fish',
    name: 'Fish Audio',
    category: 'tts',
    keyUrl: 'https://fish.audio/',
    docsUrl: 'https://docs.fish.audio/',
    freeTier: true,
    limits: 'Free tier',
    freeTierDetail: '50+ языков, backed by Novita AI',
    description: 'Многоязычный',
    supportsRussian: true,
    requiresCard: false,
  },

  // === STT ===
  {
    id: 'whisper-openai',
    name: 'OpenAI Whisper API',
    category: 'stt',
    keyUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs/guides/speech-to-text',
    freeTier: false,
    limits: '$0.006/мин',
    freeTierDetail: 'Fallback для SRT',
    description: 'Уже в плане как fallback',
    supportsRussian: true,
    requiresCard: true,
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    category: 'stt',
    keyUrl: 'https://www.assemblyai.com/dashboard',
    docsUrl: 'https://www.assemblyai.com/docs',
    freeTier: true,
    limits: 'Free tier limited',
    freeTierDetail: 'Хорош для длинных аудио',
    description: 'STT для субтитров',
    supportsRussian: true,
    requiresCard: false,
  },
  {
    id: 'deepgram-stt',
    name: 'Deepgram Nova STT',
    category: 'stt',
    keyUrl: 'https://console.deepgram.com/',
    docsUrl: 'https://developers.deepgram.com/docs',
    freeTier: true,
    limits: '$200 кредитов на старт',
    freeTierDetail: 'Быстрый STT',
    description: 'Для субтитров',
    supportsRussian: true,
    requiresCard: false,
  },
];

// Composite key to avoid collision between LLM and TTS with same id (e.g. openai)
export const PROVIDER_LINKS_MAP = new Map(PROVIDER_LINKS.map(p => [`${p.category}:${p.id}`, p]));
// Fallback map for legacy id-only lookup (last wins, but we try category first)
const LEGACY_MAP = new Map(PROVIDER_LINKS.map(p => [p.id, p]));

export function getProviderLink(id: string, category?: ProviderCategory): ProviderLink | undefined {
  if (category) {
    const composite = PROVIDER_LINKS_MAP.get(`${category}:${id}`);
    if (composite) return composite;
    if (id === 'openai-tts' && category === 'tts') {
      return PROVIDER_LINKS_MAP.get('tts:openai') || PROVIDER_LINKS_MAP.get('tts:openai-tts');
    }
    if (id === 'openai' && category === 'tts') {
      return PROVIDER_LINKS_MAP.get('tts:openai') || PROVIDER_LINKS_MAP.get('tts:openai-tts');
    }
  }
  return PROVIDER_LINKS_MAP.get(`llm:${id}`) || PROVIDER_LINKS_MAP.get(`tts:${id}`) || PROVIDER_LINKS_MAP.get(`stt:${id}`) || LEGACY_MAP.get(id);
}

export function getProvidersByCategory(cat: ProviderCategory): ProviderLink[] {
  return PROVIDER_LINKS.filter(p => p.category === cat);
}
